title: 'Release mm-dd-yyyy'
labels: 'General Release'
body:
- type: dropdown
  id: release-type
  attributes:
    label: What type of release is this?
    options: 
        - Regular
        - quickfix
  validations:
    required: true 
- type: textarea
  id: improvements
  attributes:
    label: Deployment Steps
    description: "What are the top 3 improvements we could make to this project?"
    value: |
      ## Deployment Runbooks

      [login.salesforce.com]

      ## Prod Deployment

      [login.salesforce.com]
  validations:
    required: true 
