title: "[Release mm-dd-yyyy]"
labels: "[General Release]"
body:
- type: markdown
  attributes:
    value: "Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord."
- type: textarea
  attributes:
    label: Post Deployment
- type: textarea
  attributes:
    label: Release Discussion
